/**
 * MOCK DATA — Replace with real API responses
 * All hardcoded demo content is centralized here for easy backend integration.
 */

export const MOCK_ASSET = {
  bankName: "State Bank of India",
  assetType: "Fixed Deposit",
  status: "Dormant",
  amount: "₹5,00,000",
  statusLabel: "Drafting Legal Docket",
};

export const SCAN_LOADING_TEXTS = [
  "Connecting to RBI UDGAM...",
  "Querying Bima Bharosa...",
  "Analyzing Matches...",
];

export const CHAT_SCRIPT = {
  initialMessage: `I see we are recovering an ${MOCK_ASSET.bankName} ${MOCK_ASSET.assetType}. To generate your Indemnity Bond, I need to ask a few questions. Was there a registered nominee?`,
  nomineeYes: "Yes, Nominee Exists",
  nomineeNo: "No Nominee",
  heirsQuestion: "Understood. How many legal heirs (children/spouse) are currently living?",
};

export const DOCUMENTS = [
  {
    title: "SBI Death Claim Form",
    tag: "Auto-filled",
    tagColor: "bg-primary/10 text-primary",
    previewContent: `STATE BANK OF INDIA
DEATH CLAIM FORM — FIXED DEPOSIT

Date: ${new Date().toLocaleDateString("en-IN")}
Ref: HQ/SBI/DC/2026/00471

To,
The Branch Manager,
State Bank of India

Subject: Claim for Fixed Deposit of Deceased Account Holder

Dear Sir/Madam,

I/We, the legal heir(s) of the deceased depositor, hereby submit this claim form for the release of the Fixed Deposit amount of ${MOCK_ASSET.amount} held in the name of the deceased.

DEPOSITOR DETAILS:
- Name: [Auto-filled from PAN]
- Account Type: ${MOCK_ASSET.assetType}
- Status: ${MOCK_ASSET.status}
- Amount: ${MOCK_ASSET.amount}

CLAIMANT DECLARATION:
I/We declare that the information provided herein is true and correct to the best of my/our knowledge. I/We understand that any false statement may result in legal action.

Signature: ____________________
Date: ____________________

[This document was auto-generated by HaqSe AI Legal Engine]`,
  },
  {
    title: "Legal Heir Affidavit",
    tag: "Ready for Notary",
    tagColor: "bg-amber-50 text-amber-700 dark:bg-amber-950/30 dark:text-amber-400",
    previewContent: `AFFIDAVIT OF LEGAL HEIRSHIP

I, [Claimant Name], aged [Age] years, residing at [Address], do hereby solemnly affirm and declare as follows:

1. That the deceased, [Deceased Name], was my [Relationship] and passed away on [Date of Death].

2. That I am one of the legal heirs of the deceased as per the Indian Succession Act, 1925 / Hindu Succession Act, 1956.

3. That the following persons are the surviving legal heirs of the deceased:
   a) [Heir 1 — Name, Relationship, Age]
   b) [Heir 2 — Name, Relationship, Age]

4. That no other person has any right, title, or interest in the estate of the deceased other than the persons mentioned above.

5. That this affidavit is being made for the purpose of claiming the ${MOCK_ASSET.assetType} of ${MOCK_ASSET.amount} held with ${MOCK_ASSET.bankName}.

VERIFICATION:
I solemnly verify that the contents of this affidavit are true and correct to the best of my knowledge and belief.

Deponent: ____________________
Date: ____________________
Place: ____________________

NOTARY SEAL:

[This document was auto-generated by HaqSe AI Legal Engine]`,
  },
  {
    title: "Indemnity Bond",
    tag: "Ready for Signature",
    tagColor: "bg-blue-50 text-blue-700 dark:bg-blue-950/30 dark:text-blue-400",
    previewContent: `INDEMNITY BOND

KNOW ALL MEN BY THESE PRESENTS:

This Indemnity Bond is executed on this ${new Date().toLocaleDateString("en-IN")} by:

[Claimant Name], S/o, D/o, W/o [Parent/Spouse Name], aged [Age] years, residing at [Full Address], hereinafter referred to as the "Indemnifier".

IN FAVOUR OF:
${MOCK_ASSET.bankName}, a body corporate constituted under the State Bank of India Act, having its registered office at Mumbai, hereinafter referred to as the "Bank".

WHEREAS:
1. The deceased, [Deceased Name], maintained a ${MOCK_ASSET.assetType} bearing Account No. [XXXXXXXXXX] with the Bank having a balance of ${MOCK_ASSET.amount}.

2. The deceased passed away intestate / without nominating any person for the said deposit.

3. The Indemnifier claims to be the legal heir of the deceased and has requested the Bank to release the said amount.

NOW THIS BOND WITNESSETH:
The Indemnifier hereby agrees to indemnify and keep indemnified the Bank against all losses, claims, demands, actions, proceedings, damages, costs, and expenses that may arise from the Bank releasing the said amount.

IN WITNESS WHEREOF, the Indemnifier has executed this Bond on the date first mentioned above.

Indemnifier Signature: ____________________
Witness 1: ____________________
Witness 2: ____________________

[This document was auto-generated by HaqSe AI Legal Engine]`,
  },
];

export const DOCKET_FILE_CONTENT = `
══════════════════════════════════════════════════════════════
                 CONFIDENTIAL LEGAL DOCKET
                       HAQSE AI
══════════════════════════════════════════════════════════════

Generated: ${new Date().toLocaleString("en-IN")}
Case Reference: HQ/2026/CLAIM/00471
Asset: ${MOCK_ASSET.bankName} — ${MOCK_ASSET.assetType}
Claimed Amount: ${MOCK_ASSET.amount}

──────────────────────────────────────────────────────────────
DOCUMENT 1: SBI DEATH CLAIM FORM
──────────────────────────────────────────────────────────────
${DOCUMENTS[0].previewContent}

──────────────────────────────────────────────────────────────
DOCUMENT 2: LEGAL HEIR AFFIDAVIT
──────────────────────────────────────────────────────────────
${DOCUMENTS[1].previewContent}

──────────────────────────────────────────────────────────────
DOCUMENT 3: INDEMNITY BOND
──────────────────────────────────────────────────────────────
${DOCUMENTS[2].previewContent}

══════════════════════════════════════════════════════════════
                    END OF LEGAL DOCKET
  This docket was auto-generated by HaqSe AI Legal Engine.
     Secured by RBI Account Aggregator Framework.
══════════════════════════════════════════════════════════════
`;

export const FOOTER_TEXT = "Secured by RBI Account Aggregator Framework | RVCE Fintech 2026";

export const LEGAL_TERMS: Record<string, string> = {
  "Indemnity Bond": "A safety document protecting the bank from future legal disputes over the released funds.",
  "Legal Heir": "A person legally entitled to inherit the estate of someone who has passed away.",
  "Affidavit": "A written sworn statement confirmed by oath, used as evidence in legal proceedings.",
  "Nominee": "A person designated by the account holder to receive the funds upon their death.",
  "Intestate": "When a person dies without leaving a valid will.",
  "Notarized": "A document officially authenticated by a licensed notary public.",
  "Dormant": "A bank account with no transactions for a prolonged period, typically 10+ years.",
  "UDGAM": "RBI's Unclaimed Deposits Gateway to Access and Monitor — a portal to search unclaimed deposits.",
  "Deponent": "The person who makes a sworn statement (affidavit) under oath.",
};
